### ISSUE TITLE
help with add logo on the main page

### ISSUE THREAD

**Issue by DarkLinuxHero** [ShahriarShafin/NodeMcu-ESP8266_Fake_sign_in#2]
i will like to know how implement the code to add logo png on the captive webpage. please any help is welcome. thank you. this sketch is amazing.
![login](https://user-images.githubusercontent.com/63241144/117227583-d2df4980-ae1f-11eb-99cd-ea265759c6d6.jpg)

**Comment by shahriarshafin** [comment]
Directly you cannot add a png/jpg file. You have to convert it to[ base24 image](https://www.base64-image.de/) <br>This is [how](https://gist.github.com/shahriarshafin/9d675840e61efcd12625be62c70d7f44#file-fake-sign-in-ino-L59) you can add a logo. check line no [59](https://gist.github.com/shahriarshafin/9d675840e61efcd12625be62c70d7f44#file-fake-sign-in-ino-L59) in the `<img>` tag. <br>Let me know if you encounter any problems.<br> Thank You.


<img src="https://user-images.githubusercontent.com/32214710/117387358-976d7980-af0a-11eb-975c-47a5fa40c842.jpg" alt="drawing" width="400"/>

**Comment by DarkLinuxHero** [comment]
i have an error with arduino ide but after trying different ways i could compile, but everythings change in visual.
![WhatsApp Image 2021-05-07 at 23 02 11](https://user-images.githubusercontent.com/63241144/117512191-ce3da100-af97-11eb-95d9-63f81291b2f7.jpeg)

**Comment by shahriarshafin** [comment]
[mail me](connect.shafin@gamil.com) your logo and code

**Comment by DarkLinuxHero** [comment]
i send you my code and logo to your email

**Comment by sknazmul3464** [comment]
polaibina khara
